# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: BDBA scan

# https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
permissions:
  # Grant read permissions to repository in case it is not a forked public
  # repository, but a private repository that was created manually.
  contents: read

  # Grant read permissions to private container images.
  packages: read

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
      - '!**/.clang-format'
      - '!**/COPYING'
      - '!**/LICENSE'
      - '!.github/**'
      - '.github/workflows/bdba.yml'
      - '!.gitignore'
      - '!cmake/manifests/**'
      - '!container/**'
      - '!docs/**'
      - '!scripts/**'

jobs:
  build:
    runs-on:
      - self-hosted
      - linux
      - x64
      - container

    container:
      image: ghcr.io/intel/fpga-runtime-for-opencl/ubuntu-20.04-dev:main

    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    environment: bdba

    steps:
      - name: change ownership of workspace to current user
        run: sudo chown -R build:build .

      - name: checkout code
        uses: actions/checkout@v2

      - name: create build directory
        run: mkdir build

      - name: create build files
        run: |
          cd build
          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib

      - name: build runtime without unit tests
        run: |
          cd build
          ninja -v -k0 acl

      - name: create binary package
        run: |
          cd build
          cpack -G TGZ

      - name: list binary package
        run: tar tvfz build/fpga-runtime-for-opencl-*-Linux.tar.gz

      - name: submit binary package
        run: |
          printf 'Authorization: Bearer %s\nGroup: %s\n' "$BDBA_KEY" "$BDBA_GROUP" | curl \
            --fail \
            --silent \
            --header @- \
            --output upload.json \
            --upload-file build/fpga-runtime-for-opencl-*-Linux.tar.gz \
            "$BDBA_URL/api/upload/fpga-runtime-for-opencl-$GITHUB_SHA.tar.gz"
        env:
          BDBA_GROUP: ${{ secrets.BDBA_GROUP }}
          BDBA_KEY: ${{ secrets.BDBA_KEY }}
          BDBA_URL: ${{ secrets.BDBA_URL }}

      - name: print upload id
        run: jq --exit-status .results.product_id upload.json

      - name: revert ownership of workspace to root
        run: sudo chown -R root:root .
        if: always()
